version: '3'

services:
  run-jit:
    build: .
    ports:
      - 4200:4200
    command: ["npm", "run", "start"]
  run-aot:
    build: .
    ports:
      - 4200:4200
    command: ["npm", "run", "start-aot"]
